# Generated by Django 5.1.3 on 2024-11-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_product_food_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=0)),
                ('package', models.CharField(choices=[('basic', 'Basic Package'), ('premium', 'Premium Package'), ('vip', 'VIP Package')], default='basic', max_length=10)),
            ],
        ),
    ]
