# Generated by Django 5.1.3 on 2024-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='Cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='Functional_Training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='HIIT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='Strength_Training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='Yoga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='Zumba',
            field=models.BooleanField(default=False),
        ),
    ]
