# Generated by Django 5.1.3 on 2024-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_membership_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Strength_Training',
            field=models.BooleanField(default='-'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='months',
            field=models.CharField(choices=[('one month', 'one'), ('three month', 'Three'), ('six month', 'six'), ('twelve month', 'twelve')], default='one', max_length=12),
        ),
    ]
