# Generated by Django 5.1.3 on 2024-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_membership_strength_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Strength_Training',
            field=models.BooleanField(default=False),
        ),
    ]
