# Generated by Django 5.1.3 on 2024-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_alter_membership_strength_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
